main: ${project.groupId}.${project.artifactId}.${project.artifactId}
name: ${project.artifactId}
version: ${project.version}
#load: STARTUP
author: xt449
api-version: '1.14'

commands:
  pel:
    usage: /<command> [id/name]
